### ISSUE TITLE
Found no unsent transaction

### ISSUE THREAD

**Issue by ElvisPresly** [yura-pakhuchiy/znode-tool#2]
doesn't see transaction. When there were 3 confirmations the application saw pledge of 1000 coins. When there were 15 confirmations and time to start a masternoda has come it reports that there is no pledge. But masternode was all the same started despite preventions.
![screen shot 2018-08-15 at 07 39 49 am](https://user-images.githubusercontent.com/18265958/44131957-f2f76878-a05e-11e8-923a-4d35e334b492.png)
![screen shot 2018-08-15 at 07 44 10 am](https://user-images.githubusercontent.com/18265958/44131983-1aefd842-a05f-11e8-93ef-4956010c1e8b.png)

**Comment by yura-pakhuchiy** [comment]
Do you have these options in your zcoin.conf?
```
addressindex=1
spentindex=1
timestampindex=1
txindex=1
```
You need to start zcoin-qt/zcoind with `-reindex` option after adding them.
And yes, znode will start successfully if you entered all data correctly. Collateral TX check is for convenience only.

**Comment by ElvisPresly** [comment]
@yura-pakhuchiy реиндекс помог, спасибо.

**Comment by Mirllll** [comment]
Made -reindex but still dont see the input.Spending the reward from Trezor without the coin control is the problem
